[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#2563eb"
backgroundColor = "#f5f8ff"
secondaryBackgroundColor = "#dbeafe"
textColor = "#1e3a8a"
font = "sans serif"
